### ISSUE TITLE
Dockerized version

### ISSUE THREAD

**Issue by ralexrdz** [MongoDB-Cowboys/Monalize#7]
Is there a Dockerized example of this library?

I would like to use it on mongo docker containers

**Comment by ku9nov** [comment]
Actually, the location of your database doesn't matter. All you need is access to it from the server or local machine and the presence of MongoDB Database Tools on that machine. You can install them from here: https://www.mongodb.com/docs/database-tools/installation/installation/.

However, since data collection occurs in three stages, we are missing the last two stages here. The simplest option for you would be to install it directly in a container and run it there, but I am not sure which specific Docker images you are using, and there may be issues with installing dependencies.

It is also possible to run an Ubuntu container alongside the installed Mongo and dependencies, mounting the MongoDB log file to it.

There are many options, and they are not all straightforward. Therefore, I have decided to address this issue in the near future, improve the application, and add support for extracting data from Docker containers.

**Comment by ku9nov** [comment]
Hello, @ralexrdz 

You can find the updated version with Docker log reading support here: https://github.com/MongoDB-Cowboys/Monalize/tree/feature/complex_upgrade
I attempted to directly implement native Docker container log reading using the Golang module, but unfortunately, the MongoDB container returns logs with binary data, which took me a lot of time to process. So, this feature might be implemented a little later. Currently, a similar approach to the previous one is being used through the shell.

Please pay attention to the updated README and changelog file. Now, to correctly process logs in Docker, you need to pass the container name.

The full release will be slightly delayed, but for now, this functionality should be sufficient for you. Let me know about the results and any issues that arise.

**Comment by ku9nov** [comment]
Added Docker support, check CHANGELOG.md and README.md.

New version 1.2.0 is released.
